### ISSUE TITLE
hmipserver listDevices

### ISSUE THREAD

**Issue by hobbyquaker** [eq-3/occu#43] opened 2017-04-13 16:28 UTC
When responding to a `listDevices` after I made an init on hmipserver it always responds with a `deleteDevices` for all devices and sends an `addDevices` directly after that with the same devices again. Wolfgang told me to include not only ADDRESS and VERSION in my answer to `listDevices`, but send all device infos, but that doesn't work either.

**Comment by jens-maus** [comment] 2017-04-13 17:06
I recognized the same implementing HmIP support in ioBroker. There I added a workaround, thought. But I also believe it should be fixed in HMServer instead.

**Comment by eq-3-occu** [comment] 2017-04-14 09:12
This is not a bug. It was a  conscious decision to check more attributes for Homematic IP. The changed behavior will be documented in the next version of "HomeMatic XML-RPC-Schnittstelle - HmIP Addendum" (http://www.eq-3.de/service/downloads.html?id=182). The following attributes must be included:

ADDRESS 
VERSION 
AES_ACTIVE
CHILDREN
DIRECTION
FIRMWARE
FLAGS
GROUP
INDEX
INTERFACE
LINK_SOURCE_ROLES
LINK_TARGET_ROLES
PARAMSETS
PARENT
PARENT_TYPE
RF_ADDRESS
ROAMING
RX_MODE
TEAM
TEAM_CHANNELS
TEAM_TAG
TYPE

**Closed as completed by eq-3-occu** 2017-04-14 09:12 UTC

**Comment by hobbyquaker** [comment] 2017-04-14 09:18
as i said, it doesnt work, even when i send all the attributes. Hmipserver still responds with a deleteDevices for all devices.

**Comment by hobbyquaker** [comment] 2018-08-25 18:39
@eq-3-occu reminder: still not documented in the HmIP Addendum
